[workspace]
resolver = "2"

members = ["indexland", "indexland_derive"]

package.version = "0.2.0"
package.license = "MIT"
package.authors = ["Christian Schwarz <cmrs@cmrs.io>"]
package.repository = "https://github.com/cmrschwarz/indexland"
package.edition = "2021"
package.rust-version = "1.80"
package.categories = ["data-structures", "memory-management", "rust-patterns"]
package.keywords = ["index", "collection", "container", "vec", "slice"]
